branches:
    only:
        - master
# sudo: required
language: php
# php:
#     - '5.5'
#     - '5.6'
    
# install:
#     - composer install
# script: 
#     - wget -O box.phar https://github.com/box-project/box2/releases/download/2.7.5/box-2.7.5.phar
#     - php -d phar.readonly=0 box.phar build && sudo mv dix.phar /usr/local/bin/dix && sudo chmod +x /usr/local/bin/dix
#     - vendor/bin/phpunit
notifications:
email: false